---
# handlers file for ./roles/dhis2
- name: Reload Postgres
  vars:
    ansible_host: "{{ hostvars[inventory_hostname]['database_host'] if ansible_connection == 'lxd' else  hostvars[hostvars[inventory_hostname]['database_host']]['ansible_host']}}"
  delegate_to: "{{ hostvars[inventory_hostname]['database_host'] }}"
  ansible.builtin.service:
    name: postgresql
    state: reloaded
  when:
    - database_host is defined 

# stopping tomcat9
- name: Stop Tomcat
  ansible.builtin.systemd:
    name: tomcat9
    state: stopped
    daemon_reload: yes
  when: inventory_hostname in groups['instances']

# starting tomcat9 
- name: Start Tomcat
  ansible.builtin.systemd:
    name: tomcat9
    state: started
    daemon_reload: yes
  when: inventory_hostname in groups['instances']

# restarting tomcat 9 
- name: Restart Tomcat
  ansible.builtin.systemd:
    name: tomcat9
    state: restarted
    daemon_reload: yes
  when: inventory_hostname in groups['instances']

- name: Reload Nginx
  connection: community.general.lxd
  ansible.builtin.service:
    name: nginx
    state: reloaded
  when: inventory_hostname in 'proxy'

