---
# handlers file for ./roles/dhis2
# stopping tomcat9
- name: Stop Tomcat
  connection: community.general.lxd
  ansible.builtin.service:
    name: tomcat9
    state: stopped
  delegate_to: "{{ item.name }}"
  loop: "{{ instances }}"

# starting tomcat9 
- name: Start Tomcat
  connection: community.general.lxd
  ansible.builtin.service:
    name: tomcat9
    state: started
  delegate_to: "{{ item.name }}"
  loop: "{{ instances }}"

# restarting tomcat 9 
- name: Restart Tomcat
  connection: community.general.lxd
  ansible.builtin.service:
    name: tomcat9
    state: restarted
  delegate_to: "{{ item.name }}"
  loop: "{{ instances }}"

- name: Reload Nginx
  connection: community.general.lxd
  delegate_to: proxy
  ansible.builtin.service:
    name: nginx
    state: reloaded

- name: Reload Postgres
  delegate_to: postgres
  ansible.builtin.service:
    name: postgresql
    state: reloaded


  

