---
# tasks below  are run on the containers/vms
# Adding postgresql signing key
- name: Add an Apt signing key
  ansible.builtin.apt_key:
    url: "https://www.postgresql.org/media/keys/ACCC4CF8.asc" # https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present
  when: inventory_hostname in groups['databases']

 # add postgres apt repository 
- name: Add Postgres APT repository into sources list
  ansible.builtin.apt_repository:
    repo: "deb https://apt.postgresql.org/pub/repos/apt focal-pgdg main"
    update_cache: true
    state: present
  when: inventory_hostname in groups['databases']

# Install postgresql and python module for Postgres
- name: "Install postgres Version {{ postgresql_version }}"
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600
    name: 
      - ca-certificates
      - postgresql-{{ postgresql_version }}
      - postgresql-client-{{ postgresql_version }}
      - postgresql-{{ postgresql_version }}-postgis-2.5
      - python3-psycopg2 # python module for postgres
  when: inventory_hostname in groups['databases']
  
# Check postgresql Version
- name: Check posgresql Version
  become: true
  become_method: sudo
  become_user: postgres
  community.postgresql.postgresql_info:
    filter: ver*
  register: postgresql_version_info
  when: inventory_hostname in groups['databases']

- name: Allow posgress listening on network
  lineinfile:
    dest: /etc/postgresql/{{ postgresql_version_info.version.major }}/main/postgresql.conf
    regex: "^#?listen_addresses"
    line: "listen_addresses '*'"
  when: inventory_hostname in groups['databases']
  notify: Restart Postgres
