# Allow ssh port 22. 
- name: Allow ssh on port 22
  community.general.ufw:
    rule: limit
    port: "{{ ssh_port | default('22') }}"
    src: 0.0.0.0/0
    proto: tcp
    comment: Allow ssh access to the instance
  when: ansible_connection == "ssh"

# Allow access from dhis2 instances to postgresql port 5432
- name: Allow access from dhis2 instances 
  community.general.ufw:
    rule: allow
    port: "{{ postgresql_port | default('5432')}}"
    src: "{{ hostvars[item]['ansible_host'] }}"
    proto: tcp
    comment: "Allow access from {{ item }} instance "
    state: enabled
  loop: "{{ groups['instances'] }}"

# Allow port 4949 for munin communication
- name: Allow port 4949 from munin server.
  community.general.ufw:
    rule: allow
    port: "{{ munin_node_port | default('4949') }}"
    src: "{{ hostvars[item]['ansible_host'] }}"
    proto: tcp
    comment: Allow access from {{item}} monitoring server
  loop: "{{ groups['monitoring'] }}"

