---
# Can either be ssh or lxd related tasks
- include_tasks: "{{ansible_connection}}.yml"
  when: inventory_hostname in groups['databases']

# installing postgresql database
- include_tasks: postgresql_install.yml
  when: inventory_hostname in groups['databases']

- meta: flush_handlers
  
