---
- name: "Include tasks specific to setup over {{ ansible_connection }}"
  include_tasks: "{{ ansible_connection }}.yml"
  when: inventory_hostname in groups['databases']

- name: Installing postgresql database
  include_tasks: common.yml
  when: inventory_hostname in groups['databases']
  
