---
# Can either be ssh or lxd related tasks
- name: "Including tasks | {{ ansible_connection }}"
  ansible.builtin.include_tasks: "{{ ansible_connection }}.yml"
  when: inventory_hostname in groups['databases']

# installing postgresql database
- name: "Installing postgres over {{ ansible_connection }}"
  ansible.builtin.include_tasks: pg_install.yaml
  when: inventory_hostname in groups['databases']
