---
# Can either be ssh or lxd related tasks
- name: "Including database {{ ansible_connection }} connection tasks"
  include_tasks: "{{ansible_connection}}.yml"
  when: inventory_hostname in groups['databases']

# installing postgresql database
- name: "Installing postgres over {{ansible_connection}} connection"
  include_tasks: postgresql_install.yml
  when: inventory_hostname in groups['databases']
