---
# tasks below are executed on a postgresql host
# Adding postgresql signing key
- name: Add an Apt signing key
  ansible.builtin.apt_key:
    url: "https://www.postgresql.org/media/keys/ACCC4CF8.asc"
    state: present

 # add postgres apt repository 
- name: Add Postgres APT repository into sources list
  ansible.builtin.apt_repository:
    repo: "deb https://apt.postgresql.org/pub/repos/apt focal-pgdg main"
    update_cache: true
    state: present

# Install postgresql and python module for Postgres
- name: "Install postgres Version {{ postgresql_version }}"
  ansible.builtin.apt: 
    update_cache: yes
    cache_valid_time: 3600
    name: 
      - ca-certificates
      - postgresql-{{ postgresql_version }}
      - postgresql-client-{{ postgresql_version }}
      - postgresql-{{ postgresql_version }}-postgis-2.5
      - python3-psycopg2 # python module for postgres
      - libdbd-pg-perl
  
# Check postgresql Version
- name: Check posgresql Version
  become: true
  become_method: sudo
  become_user: postgres
  community.postgresql.postgresql_info:
    filter: ver*
  register: postgresql_version_info

# Fixing pg_hba.conf permissions
- name: Fixing pg_hba.conf permissions, allowing instances to connect
  become: True
  lineinfile:
    path: /etc/postgresql/{{postgresql_version_info.version.major}}/main/pg_hba.conf
    insertafter: EOF
    line: "host    {{item}}   {{item}}  {{hostvars[item]['ansible_host']}}/32   md5"
  loop: "{{ groups['instances'] }}"
  when:
    - inventory_hostname == hostvars[item]['database_host'] 
  notify: Restart Postgres

- name: Allow posgress listening on network
  lineinfile:
    dest: /etc/postgresql/{{ postgresql_version_info.version.major }}/main/postgresql.conf
    regex: "^#?listen_addresses"
    line: "listen_addresses '*'"
  notify: Restart Postgres

# Allow access from dhis2 instances to postgresql port 5432
- name: Firewall | allow access from the instance(s)
  community.general.ufw:
    rule: allow
    port: "{{ postgresql_port | default('5432')}}"
    src: "{{ hostvars[item]['ansible_host'] }}"
    proto: tcp
    comment: "Allow access from {{ item }} instance "
    state: enabled
  loop: "{{ groups['instances'] }}"
  when: inventory_hostname == hostvars[item]['database_host']

- name: Flush Handlers
  meta: flush_handlers
