# Allow ssh port 22. 
- name: Allow ssh on port 22
  community.general.ufw:
    rule: limit
    port: "{{ ssh_port | default('22') }}"
    src: 0.0.0.0/0
    proto: tcp
    comment: Allow ssh access to the instance
- name: Install acl package, needed when switching to postgres user
  become: true
  ansible.builtin.apt:
    name: acl
    state: present
    update_cache: yes
  when: inventory_hostname in groups['databases']
