- name: Install acl package, needed when switching to postgres user
  become: true
  ansible.builtin.apt:
    name: acl
    state: present
    update_cache: yes
  when: inventory_hostname in groups['databases']
