- hosts: localhost
  connection: local
  pre_tasks:
    - name: Load default variables from a file
      include_vars:
        file: containers.yml
        name: containers
  tasks:
    - name: dump vars
      debug:
        msg: "{{ containers }}"
