- name: "Updating and Upgrading"
  ansible.builtin.apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400

# - name: "Adding artemis application user"
- name: "Installing java11"
  ansible.builtin.apt:
    name: openjdk-11-jre-headless

- name: "Download and extract artemis"
  ansible.builtin.unarchive:
    src: "{{ artemis_download_url }}"
    dest: "{{ artemis_install_dir }}"
    remote_src: yes
    owner: "{{ artemis_user.name }}"
    group: "{{ artemis_user.group }}"
    creates: "{{ artemis_home }}/bin/artemis"
  notify: restart broker

- name: "Create link"
  ansible.builtin.file:
    src: "{{ artemis_home }}"
    dest: "{{ artemis_home_symlink }}"
    state: link
    owner: "{{ artemis_user.name }}"
    group: "{{ artemis_user.group }}"
