---
- name: "Ensure acl packate is installed"
  become: true
  ansible.builtin.apt:
    name: acl
    state: present
    update_cache: yes

- name: "Allow ssh on port 22"
  community.general.ufw:
    rule: limit
    port: "{{ ssh_port | default('22') }}"
    src: 0.0.0.0/0
    proto: tcp
    comment: Allow ssh access to the instance
