- name: Configure host to NAT to the proxy container
  become: true
  become_user: root
  ansible.builtin.blockinfile:
    path: /etc/ufw/before.rules
    insertbefore: BOF
    marker: "# {mark} NAT configuration"
    block: |
      *nat
      -F
      :PREROUTING ACCEPT [0:0]
      {% for container in containers %}
      {% if container.name == "proxy" %}
      -A PREROUTING -i {{ ansible_default_ipv4.interface }} -p tcp --dport 80 -j  DNAT --to-destination {{container.ip}}:80
      -A PREROUTING -i {{ ansible_default_ipv4.interface }} -p tcp --dport 443 -j  DNAT --to-destination {{container.ip}}:443
      {% endif %}
      {% endfor %}
      # setup routing
      -A POSTROUTING -s {{lxd_network}} ! -d {{lxd_network}} -j MASQUERADE
      COMMIT
  notify: 
    - reload ufw

# lxd proxy device.   
