---
# Allow access from dhis2 instances to postgresql port 5432
- name: Allow http port 80 
  community.general.ufw:
    rule: allow
    port: "{{ http_port | default('80')}}"
    proto: tcp
    comment: open http port
    state: enabled

# Allow https port from the internet 
- name: Allow https port.
  community.general.ufw:
    rule: allow
    port: "{{ https_port | default('443') }}"
    proto: tcp
    comment: open https port 

