# tasks file for ./roles/proxy
- name: Create proxy container
  become: False
  vars:
    ansible_connection: local
  community.general.lxd_container:
    name: "{{ inventory_hostname }}"
    state: started
    profiles: ["default"]
    ignore_volatile_options: false
    timeout: 600
    source:
      type: image
      mode: pull
      #server: https://images.linuxcontainers.org
      server: https://cloud-images.ubuntu.com/releases
      fingerprint: e3e1bd82cdc7
      protocol: simplestreams
      #alias: ubuntu/{{containers[0].guest_os | default(20.04)}}
    devices:
      eth0:
        nictype:  "bridged"
        parent:   "{{ containers[0].network | default ('lxdbr0') }}"
        type:     "{{ containers[0].interface_type | default ('nic') }}"
        ipv4.address: "{{ hostvars[inventory_hostname]['ansible_host'] | ipaddr(lxd_network) | default(omit)}}" 
  delegate_to: 127.0.0.1
  when:
    - inventory_hostname in groups['web'] 
    - proxy_is_enabled | bool
  # run_once: True
