# tasks file for ./roles/proxy
- name: Create proxy container
  become: True
  vars:
    ansible_connection: local
  community.general.lxd_container:
    name: "{{ inventory_hostname }}"
    state: started
    profiles: ["default"]
    ignore_volatile_options: false
    timeout: 600
    source:
      type: image
      mode: pull
      #server: https://images.linuxcontainers.org
      server: https://cloud-images.ubuntu.com/releases
      protocol: simplestreams
      alias: "{{ guest_os }}/{{guest_os_arch | default('amd64')}}"
    devices:
      #"80":
      #  listen: tcp:0.0.0.0:80
      #  connect: tcp:127.0.0.1:80
      #  # nat: 'true'
      #  type: proxy
      #"443":
      #  listen: tcp:0.0.0.0:443
      #  connect: tcp:127.0.0.1:443
      #  #nat: 'true'
      #  type: proxy 
      eth0:
        nictype: "bridged"
        parent: "{{ lxd_bridge_interface | default ('lxdbr0') }}"
        type: "nic"
        ipv4.address: "{{ hostvars[inventory_hostname]['ansible_host'] | ansible.utils.ipaddr(lxd_network) | default(omit)}}" 
  when:
    - inventory_hostname in groups['web'] 
    - proxy is defined

