---
- name: include {{ ansible_connection }} related tasks 
  include_tasks: "{{ ansible_connection }}.yml"
# run proxy specifig tasks
- name: Proxy setup 
  include_tasks: "{{proxy}}.yml"
  when: proxy_is_enabled

