---
- name: include {{ ansible_connection }} related tasks 
  include_tasks: "{{ ansible_connection }}.yml"
  when: inventory_hostname in groups['web'] and proxy_is_enabled | bool 

- name: Proxy setup 
  include_tasks: "{{proxy}}.yml"
  when: inventory_hostname in groups['web'] and  proxy_is_enabled  | bool 

