---
# tasks file for ./roles/proxy
- name: Install nginx
  apt:
    name: nginx
    update_cache: yes
    cache_valid_time: 3600
    state: latest

- name: Disabling nginx version show
  lineinfile:
    dest: /etc/nginx/nginx.conf
    regex: '.*server_tokens off'
    line: "\tserver_tokens off;"
    insertafter: "types_hash_max_size"
  notify: reload nginx

- name: Remove default nginx site 
  file: name=/etc/nginx/sites-enabled/default state=absent


