---
# handlers file for ./roles/proxy
- name: reload ufw
  connection: local
  become: true
  become_user: root
  community.general.ufw:
    state: reloaded

- name: Reload Nginx
  service:
    name: nginx
    state: reloaded

- name: Reload Apache2
  service:
    name: apache2
    state: reloaded


