---
# handlers file for ./roles/postgresql
# Restart postgresql service
- name: Restart Postgres
  ansible.builtin.service:
    name: postgresql
    state: restarted

# Reload postgresql service 
- name: Reload Postgres
  ansible.builtin.service:
    name: postgresql
    state: reloaded
- name: restart munin-node
  service: name=munin-node state=restarted
