- hosts: all
  gather_facts: yes
    # prompt users to enter variables 
#vars_prompt:
#- name: "instance_name"
#      prompt: "Provision a new dhis2 instance\nDatabase must already be setup prior to running.\nInstance name:"
#default: "dhis2"
#    private: no
  
  roles:
    - role: dhis2
