- hosts: all
  vars:
    ansible_connection: local
  tasks:
  - name: Create lxd containers
    delegate_to: 127.0.0.1
    community.general.lxd_container:
      name: "{{ inventory_hostname }}"
      state: started
      profiles: [ default ]
      wait_for_ipv4_addresses: true
      ignore_volatile_options: false
      timeout: 600
      source:
        type: image
        mode: pull
        server: https://cloud-images.ubuntu.com/releases
        protocol: simplestreams 
        fingerprint: e3e1bd82cdc7
      devices:   
        eth0:
           nictype:  "bridged"
           parent:   "lxdbr0"
           type:     "nic"
           ipv4.address: "{{ hostvars[inventory_hostname]['ansible_host'] | ansible.utils.ipaddr(lxd_network) | default(omit)}}" 
