---
- hosts: 127.0.0.1
  become: True
  gather_facts: False
  roles:
    - pre_requisites

- gather_facts: False
  force_handlers: True
  become: True
  hosts: all:!127.0.0.1
  vars_files:
    - vars/vars.yml
  roles:
    - role: postgres
    - role: dhis2
    - role: proxy
    - role: monitoring
  tasks:
    - include_tasks: tasks/unattended_upgrades.yml
      when: 
      - unattended_upgrades is defined
      - unattended_upgrades | bool == true
  handlers:
    - import_tasks: tasks/handlers.yml
