# Allow access from proxy  to tomcat port 8080
- name: Allow access to port 8080 from proxy
  community.general.ufw:
    rule: allow
    port: "{{ tomcat_port | default('8080')}}"
    src: "{{ hostvars[item]['ansible_host'] }}"
    proto: tcp
    state: enabled 
    comment: "tomcat access from the proxy"
  loop: "{{ groups['web'] }}"

# Allow port 4949 for munin communication
- name: Allow access to  port 4000 from proxy
  community.general.ufw:
    rule: allow
    port: "{{ munin_node_port | default('4000') }}"
    src: "{{ hostvars[item]['ansible_host'] }}"
    proto: tcp
    comment: Glowroot monitor access from proxy
    state: enabled 
  loop: "{{ groups['web'] }}"
  when: app_monitoring is defined and app_monitoring=="glowroot"

