## Creating dhis2 instance(s)
  # Include connection specific tasks
- name: "Include tasks specific to setup over {{ ansible_connection }}"
  include_tasks: "{{ ansible_connection }}.yml"

- name: Include dhis2 instnce setup tasks  
  include_tasks: common.yml

