---
# Include connection specific tasks
- include_tasks: "{{ ansible_connection }}.yml"
  when: inventory_hostname in groups['instances']

- include_tasks: postgresql_db.yml
  when: > 
    inventory_hostname in groups['instances'] or 
    inventory_hostname in groups['databases']

# this deploys dhis2 tomcat application. 
- include_tasks: dhis2_setup.yml
  when: inventory_hostname in groups['instances']

- include_tasks: "{{app_monitoring}}.yml"
  when:
    - inventory_hostname in groups['instances'] 
    - app_monitoring is defined 

- name: Flush Handlers 
  meta: flush_handlers
