# Nginx location configuration
- name: Adding location configuration to nginx confuration
  blockinfile:
    path: "/etc/nginx/sites-available/{{fqdn}}"
    marker: "# {mark} {{ item }} block configuration."
    insertafter: "# Proxy pass to the backend"
    block: |2
        location /{{item}} {
          proxy_pass http://{{ item+':8080' }}/{{item}};
          proxy_redirect off;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto https;
          proxy_buffer_size 128k;
          proxy_buffers 8 128k;
          proxy_busy_buffers_size 256k;
          }
  loop: "{{ groups['instances'] }}"
  notify: Reload Nginx
  delegate_to: proxy
  run_once: true
  when: hostvars[inventory_hostname]['proxy_is_enabled'] 
- meta: flush_handlers
