# Nginx location configuration
- name: Adding location configuration to nginx confuration
  #connection: community.general.lxd
  blockinfile:
    path: "/etc/nginx/sites-available/{{fqdn}}"
    marker: "# {mark} {{ item.name }} block configuration."
    insertafter: "# Proxy pass to the backend"
    block: |2
        location /{{item.name}} {
          proxy_pass http://{{ item.name+':8080' }}/{{item.name}};
          proxy_redirect off;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto https;
          proxy_buffer_size 128k;
          proxy_buffers 8 128k;
          proxy_busy_buffers_size 256k;
          }
  loop: "{{ instances }}"
  notify: Reload Nginx
  delegate_to: proxy

- meta: flush_handlers
