# create postgresql container,
- name: Create monitoring container
  become: True
  vars:
    ansible_connection: local
  community.general.lxd_container:
    name: "{{ inventory_hostname }}"
    state: started
    profiles: [ "default" ]
    wait_for_ipv4_addresses: true
    ignore_volatile_options: false
    timeout: 600
    source:
      type: image
      mode: pull
      server: https://cloud-images.ubuntu.com/releases
      protocol: simplestreams
      alias: "{{ guest_os }}/{{guest_os_arch | default('amd64')}}"
    devices:
      eth0:
        nictype:  "bridged"
        parent:   "{{ lxd_bridge_interface | default ('lxdbr0') }}"
        type:     "nic"
        ipv4.address: "{{ hostvars[inventory_hostname]['ansible_host'] | ansible.utils.ipaddr(lxd_network) | default(omit)}}" 
  delegate_to: 127.0.0.1
