---
# tasks file for roles/monitoring
# munin setup

# update and upgrade the server 

# install required packages 
- name: install requiered packages
  apt:
    - apache2
    - ibcgi-fast-perl
    - libapache2-mod-fcgid 


