---
# tasks file for roles/monitoring
- include_tasks: "{{ansible_connection}}.yml"
  when:
    - inventory_hostname in groups['monitoring']
    - server_monitoring is defined

- include_tasks: "{{server_monitoring}}.yml"
  when: 
    - inventory_hostname in groups['monitoring']
    - server_monitoring is defined
        
- include_tasks: "{{server_monitoring}}_node.yml"
  when: 
    - server_monitoring is defined 

- meta: flush_handlers
