---
- name: Include tasks for {{ ansible_connection }}
  ansible.builtin.include_tasks: "{{ ansible_connection }}.yml"
  when:
    - server_monitoring is defined
    - inventory_hostname in groups['monitoring']

- name: Include  server tasks for {{ server_monitoring }}
  ansible.builtin.include_tasks: "{{ server_monitoring }}-server.yml"
  when:
    - server_monitoring is defined
    - inventory_hostname in groups['monitoring']

- name: Include client tasks for {{ server_monitoring }}
  ansible.builtin.include_tasks: "{{ server_monitoring }}-client.yml"
  when:
    - server_monitoring is defined
    - inventory_hostname in groups['web'] | union(groups['monitoring']) | union(['databases'])
