---
# tasks file for roles/monitoring
- include_tasks: "{{ ansible_connection }}.yml"
  when: inventory_hostname in groups['monitoring']

- include_tasks: munin.yml
  when: inventory_hostname in groups['monitoring']

- include_tasks: munin_node.yml

