- name: Adding munin location configuration to nginx proxy 
  blockinfile:
    path: "/etc/nginx/sites-available/{{fqdn}}"
    marker: "# {mark} munin  block configuration."
    insertafter: "# Proxy pass to the backend"
    block: |2
        location /munin {
          proxy_pass http://{{hostvars['monitor']['ansible_host']+':80' }}/munin;
          proxy_redirect off;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto https;
          proxy_hide_header X-Powered-By;
          proxy_set_header X-Frame-Options "SAMEORIGIN";  # To mitigate the risk of clickjacking attacks
          proxy_set_header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload";  
          proxy_set_header X-Content-Type-Options "nosniff"; # drive-by download attacks 
          proxy_set_header X-Xss-Protection "1; mode=block"; #To leverage browser-based protections against cross-site scripting 
          proxy_hide_header Server;
          }
  notify: Reload Nginx
  when:
    - server_monitoring is defined and server_monitoring == "munin"
    - inventory_hostname | regex_search('(proxy|rps)')
  # delegate_to: proxy
  # run_once: true
