---
# Adding postgresql signing key
- name: Adding  postgresql repository 
  block: 
  # adding apt signing key
  - name: Adding postgresql repo signing key 
    ansible.builtin.get_url:
      url: "https://www.postgresql.org/media/keys/ACCC4CF8.asc"
      dest: /etc/apt/keyrings/postgresql.asc
    register: postgres_key

   # add postgres apt repository 
  - name: Adding postgres apt repository to sources list
    ansible.builtin.apt_repository:
      repo: "deb [arch={{guest_os_arch|default('amd64')}} signed-by={{postgres_key['dest']}}] https://apt.postgresql.org/pub/repos/apt {{ hostvars[inventory_hostname]['ansible_facts']['distribution_release'] }}-pgdg main"
      update_cache: true
      state: present

# Install postgresql and python module for Postgres
- name: "Installing postgres version {{ zabbix_server_postgresql_version }}"
  ansible.builtin.apt: 
    name: 
      - ca-certificates
      - postgresql-{{ zabbix_server_postgresql_version }}
      - postgresql-client-{{ zabbix_server_postgresql_version }}
      - python3-psycopg2 
      - libdbd-pg-perl

# sometimes postgres is installed but not started
- name: Ensure postgresql is running
  become: True
  ansible.builtin.service:
    name: postgresql
    state: started
    enabled: yes
  
- name: Checking postgresql Version
  become: true
  become_method: sudo
  become_user: postgres
  community.postgresql.postgresql_info:
    filter: ver*
  register: postgresql_version_info


