---
- name: Including tasks | {{ ansible_connection }}
  ansible.builtin.include_tasks: "{{ ansible_connection }}.yml"
  when: inventory_hostname in groups['integration']

- name: Deploy jar file 
  ansible.builtin.include_tasks: jar-file-deploy.yml
   when: inventory_hostname in groups['integration']

  
