---
# tasks file for ./roles/ufw
- name: check ufw status
  become: true
  shell: ufw status
  changed_when: False
  ignore_errors: True
  register: ufw_check
- name: UFW is inactive, please
  debug:
    msg:
      - "---- UFW in disabled ---- "
      - "    Please enable it to continue with the setup"
      - "    sudo ufw allow 22   # allows ssh connections to the server"
      - "    sudo ufw enable     # starts and enables ufw"
  when: "'inactive' in ufw_check.stdout"

- meta: end_play 
  when: "'inactive' in ufw_check.stdout"

- name: Configure host to NAT to the proxy container
  become: true
  become_user: root
  ansible.builtin.blockinfile:
    path: /etc/ufw/before.rules
    insertbefore: BOF
    marker: "# {mark} NAT configuration"
    block: |
      *nat
      -F
      :PREROUTING ACCEPT [0:0]
      {% for container in containers %}
      {% if container.name == "proxy" %}
      -A PREROUTING -i {{ ansible_default_ipv4.interface }} -p tcp --dport 80 -j  DNAT --to-destination {{container.ip}}:80
      -A PREROUTING -i {{ ansible_default_ipv4.interface }} -p tcp --dport 443 -j  DNAT --to-destination {{container.ip}}:443
      {% endif %}
      {% endfor %}
      # setup routing
      -A POSTROUTING -s {{lxd_network}} ! -d {{lxd_network}} -j MASQUERADE
      COMMIT
  when: item.name | regex_search('(proxy)')
  with_items:
    - "{{ containers }}"
  notify: 
    - Reload ufw


