---
# defaults file for ./roles/proxy
SSL_TYPE: "letsencrypt"
# ansible_connection: lxd
# fqdn: "{{ undef(hint='fqdn is undefined, You must specify your FULLY QUALIFIED DOMAIN NAME on  fqdn variable')}}"

 
