---
- name: Restart Apache2
  ansible.builtin.service:
    name: apache2
    state: restarted

- name: Restart Munin
  ansible.builtin.service:
    name: munin
    state: restarted

- name: Restart Munin-Node
  ansible.builtin.service:
    name: munin-node
    state: restarted
