--- 
# install lxd with snap
- name: Install lxd with snap
  community.general.snap:
    name: lxd

# get and register lxd info
- name: LXD init
  block:
  - name: lxc info
    command: lxc info
    register: lxc_info_src0
    run_once: true
    changed_when: false

  - name: create lxd-preseed.yml
    set_fact:
      master: "{{ lookup('template', 'lxd-preseed.yml.j2') }}"
  
  - name: Backup lxd-preseed configuration to /tmp directory 
    copy:
      dest: /tmp/lxd-preseed.yml
      content: "{{ master }}"
      mode: '0644'
    changed_when: false

  - name: Initiating lxd with lxd-preseed.yml
    command: lxd init --preseed <
    args:
      stdin: "{{ master }}"
      creates: "{{ lxd_init_file_test }}"
    when: >
      (not lxd_cluster or inventory_hostname == groups.all[0])
      and
      lxc_info_src0.stdout.find('storage: \"\"') != -1
  
  - block:
    - name: Restarting LXD service initiating
      connection: local
      become: true
      command: snap restart lxd.daemon
      args:
        creates: /snap/lxd/.lxd-restart
      changed_when: false

    - file: > 
        path=/snap/lxd/.lxd-restart state=touch
        mode=u+rw,g-wx,o-rwx modification_time=preserve
        access_time=preserve
      
