--- 
# install lxd with snap
- name: Install lxd
  community.general.snap:
    name: lxd

# get and register lxd info
- name: LXD init
  block:
  - name: lxc info
    command: lxc info
    register: lxc_info_src0
    run_once: true
    changed_when: false

  - name: create lxd-preceed.yml
    set_fact:
      master: "{{ lookup('template', 'lxd-preceed.yml.j2') }}"
  
  - name: Backup lxd-preceed configuration to /tmp directory 
    copy:
      dest: /tmp/lxd-preceed.yml
      content: "{{ master }}"
      mode: '0644'
    changed_when: false

  - name: Initiating lxd with lxd-preceed.yml
    command: lxd init --preseed <
    args:
      stdin: "{{ master }}"
      creates: "{{ lxd_init_file_test }}"
    when: >
      (not lxd_cluster or inventory_hostname == groups.all[0])
      and
      lxc_info_src0.stdout.find('storage: \"\"') != -1
  
  - block:
    - name: Restarting LXD service initiating
      connection: local
      become: true
      command: snap restart lxd.daemon
      args:
        creates: /tmp/.lxd-restart
      changed_when: false

    - file: 
        path: /tmp/.lxd-restart
        state: touch
        mode: u+rw,g-wx,o-rwx
        modification_time: preserve
        access_time: preserve
      
