---
- hosts: all
  gather_facts: false
  vars_files:
    - ../vars/vars.yml
  vars:
    dhis2_base_path: hmis
  tasks:
    - name: Delete instance containers
      vars:
        ansible_connection: local
      community.general.lxd_container:
        name: "{{ dhis2_base_path }}"
        state: absent
      when: inventory_hostname in groups['instances'] and instance_state == 'deleted'
      
    # need to incoporate apache2 as well
    - name: Delete nginx location configuration on nginx
      ansible.builtin.file:
        path: /etc/nginx/conf.d/upstream/{{ hostvars[item]['dhis2_base_path'] | default(item) }}.conf
        state: absent
      loop: group['instances']
      when:
        - inventory_hostname in groups['web']
        - hostvars['item']['instance_state'] == "deleted"
      notify: Reload Nginx

    - name: Delete database
      become: true
      become_user: postgres
      community.postgresql.postgresql_db:
        name: "{{ item }}"
        state: absent
      when:
        - inventory_hostname in groups['databases']
        -  hostvars['item']['instance_state'] == "deleted"

    - name: Delete database role
      become: true
      become_user: postgres
      community.general.postgresql_user:
        name: "{{ item }}"
        state: absent
      loop: groups['instances']
      when:
        - inventory_hostname in groups['databases']
        -  hostvars[item]['instance_state'] == 'deleted'

    - name: Checking postgresql Version, needed when editing postgres config files
      become: true
      # become_method: sudo
      become_user: postgres
      community.general.postgresql_info:
        filter: ver*
      register: postgresql_version_info
      when:
        - inventory_hostname in groups['databases']
        - inventory_hostname == hostvars[dhis2_base_path]['database_host']

    # Delete entries on pg_hba.conf file
    - name: Delete {{  }} entry in pg_hba.conf config
      become: true
      ansible.builtin.lineinfile:
        path: /etc/postgresql/{{ postgresql_version_info.version.major }}/main/pg_hba.conf
        regex: host .* {{ dhis2_base_path }} .*
        state: absent
      loop: groups['instances']
      when:
        - hostvars[item]['instance_state'] is deleted
        - inventory_hostname == hostvars[item]['database_host']
        - inventory_hostname in groups['databases']
      notify: Reload Postgres

    # delete ufw rule
    - name: Firewall | Open port 5432 from dhis2 instances
      community.general.ufw:
        rule: deny
        port: "{{ postgresql_port | default('5432') }}"
        src: "{{ hostvars[item]['ansible_host'] }}"
        proto: tcp
        comment: "Allow access from {{ item }} instance "
      loop: groups['instances']
      when:
        - hostvars[item]['instance_state'] == 'deleted'
        - inventory_hostname == hostvars[item]['database_host']
        - inventory_hostname in groups['databases']

  handlers:
    - name: Reload Nginx
      ansible.builtin.service:
        name: nginx
        state: reloaded

    - name: Reload Postgres
      ansible.builtin.service:
        name: postgresql
        state: reloaded
